services:

  django:
    container_name: django
    build:
      context: ./dcelery
    
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY='django-insecure-n=h1h4@)@m3tp&)1^c+%*^)h2)w)+dc6t)qmp&byq(-x8uuqix'
      - ALLOWED_HOSTS=localhost,127.0.0.1
